### ISSUE TITLE
Very slow upload

### ISSUE THREAD

**Issue by jonm0bius** [danb35/freenas-iocage-nextcloud#100]
Hey!

I have almost no knowledge of nextcloud and freenas but got it running thanks to your script. 

For some reason tho the upload of files to the cloud is terribly slow. It seems to peak at 30mb/s for 2-3 sec and then drops to a very choppy 20kb/s to 3mb/s. So on small files there dont seem to be any issues but with bigger files its so slow it takes days to upload.

Tried to google the issue and found alot of similar post most of them seems to have solved by deactivating http2 in apache and nginx. 

Is http2 active in you script of nextcloud and if yes could you help me with how I deactivat it to see if it solves my issue?

Or maybe there is some kind of caching issue that trigger the drops in speed? 

The hardware dont seems to run into any bottlenecks. 4c/8t ryzen, 16gb ram, pool of 2 2tb in stripe and mirror for the nextcloud storage. 300/300 mbit isp

**Comment by EhabKan** [comment]
> Hey!
> 
> I have almost no knowledge of nextcloud and freenas but got it running thanks to your script.
> 
> For some reason tho the upload of files to the cloud is terribly slow. It seems to peak at 30mb/s for 2-3 sec and then drops to a very choppy 20kb/s to 3mb/s. So on small files there dont seem to be any issues but with bigger files its so slow it takes days to upload.
> 
> Tried to google the issue and found alot of similar post most of them seems to have solved by deactivating http2 in apache and nginx.
> 
> Is http2 active in you script of nextcloud and if yes could you help me with how I deactivat it to see if it solves my issue?
> 
> Or maybe there is some kind of caching issue that trigger the drops in speed?
> 
> The hardware dont seems to run into any bottlenecks. 4c/8t ryzen, 16gb ram, pool of 2 2tb in stripe and mirror for the nextcloud storage. 300/300 mbit isp

I am having teh same issue, Could you please share your solution?
