### ISSUE TITLE
adding more more than one domain access

### ISSUE THREAD

**Issue by Evert-vh** [danb35/freenas-iocage-nextcloud#101]
Hi there

I absolutely loved the script and was easy to install and get running, needed to make a few tweaks on my pfsense firewall to get access but now that everyting is running its great,

is there a way to add more than 1 domain to the install and with caddy (not familiar with caddy) the other domain can only be http auth like certbot will do so is it possible to do this afterwards and grant access from a secondary domain? and if so how will that be possible?

Regards

**Comment by danb35** [comment]
I think you may have posted on the FreeNAS forum thread and gotten an answer there.  If not, this should be possible--you'd need to add the second domain to the trusted domains configuration in Nextcloud (you can see how it's done from the command line near the end of the script, or you can edit it in to Nextcloud's config.php), and you'd need to adjust the Caddyfile to recognize the second domain.
