### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by NasKar2** [danb35/freenas-iocage-nextcloud#112]
Here is the output from a fresh install.  If gives error:'Access denied for user 'root'@'localhost' (using password: NO)'

No default gateway found for ipv6.
* Starting cloud
  + Started OK
  + Using devfs_ruleset: 12
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'
Command: mysqladmin reload failed!

**Comment by danb35** [comment]
I do see these errors when I run the script, but everything still seems to run properly.  Are you noticing problems with logging into or using Nextcloud, or seeing other errors?

**Comment by NasKar2** [comment]
Everything works fine ust seeing the error.  It happens with a fresh
install with no prior data in the nextcloud directory.

**Comment by Ornias1993** [comment]
`mysqladmin reload` isn't technically needed, it's a bit redundant but shouldn't cause any issues if it errors out.

**Comment by danb35** [comment]
The problem here was that whatever PR I merged to do this gave the `mysqladmin` credentials on one line, and the `mysqladmin reload` command on another.  Don't know why.  This is fixed in the caddyv2 branch.

**Comment by danb35** [comment]
Fixed by #135.
