### ISSUE TITLE
NO_CERT=1 stil requires CERT_EMAIL

### ISSUE THREAD

**Issue by Ramblurr** [danb35/freenas-iocage-nextcloud#113]
I'm provisioning certs myself with a transparent proxy.

I set `NO_CERT=1` and didn't set any of the other cert settings.

After the script finished, caddy wasn't started, and wouldn't start because the CERT_EMAIL setting wasn't set:

```
# service caddy restart
rc variable $caddy_cert_email is not set. Please provide a valid SSL certificate issuer email.
```

**Comment by danb35** [comment]
> wouldn't start because the CERT_EMAIL setting wasn't set:

That's correct, and documented in the README:

> This is mandatory regardless of whether you're using Let's Encrypt (Caddy won't start without it), but it's only used with Let's Encrypt.

I thought I had a check for that in the script; if not, I'll need to add it.
