### ISSUE TITLE
My own certificate

### ISSUE THREAD

**Issue by xames81** [danb35/freenas-iocage-nextcloud#119]
SELFSIGNED_CERT (to generate a self-signed certificate--this is also the setting to use if you want to use a certificate from another source).

How to put there in the script my own SSL certificate?

Thanks.

**Comment by danb35** [comment]
> How to put there in the script my own SSL certificate?

You don't put it in the script.  Instead, you run through the script, let it create the self-signed cert, and after the jail's up and running, replace that cert with your external cert.  The closing instructions from the cert will tell you where to place the files.
