### ISSUE TITLE
Update to Nextcloud v19

### ISSUE THREAD

**Issue by Snuggle** [danb35/freenas-iocage-nextcloud#120]
Nextcloud version 19.0.0 (Stable) was released, this plugin should also receive an update!

https://github.com/nextcloud/server/releases/tag/v19.0.0

**Comment by danb35** [comment]
I've tested this a little bit.  On line 291 of the script, you can change `latest-18.tar.bz2` to `latest-19.tar.bz2`, and it should install version 19 and everything else it needs.  Can you try it and make sure it works OK?

**Comment by RafalLukawiecki** [comment]
I see you have closed this issue. Does it mean this change has been ported to your setup script, ie. if I were to re-run it, would I get v19? Thank you for this very useful script, excellent work.

**Comment by danb35** [comment]
Yes, if you run the current version of the script, it will install Nextcloud 19.  If you already have the script downloaded, you can run `git pull` to update it.

**Comment by RafalLukawiecki** [comment]
Many thanks, @danb35.

I have followed your instructions and I have the separate dataset with 4 children datasets for config, db, files and themes. Should I just install into a new jail with 19, using your script? Is that the best way to upgrade from 18.0.16? Apologies for hijacking this issue with a support query, but this was the first time I have installed Nextcloud and very much thanks to your helpful script. Thank you again.

**Comment by danb35** [comment]
If you already have a running installation, I'd wait until the built-in updater gives you 19 and update that way.  Expect it to be a few weeks, possibly not until after the 19.0.1 release.  But if you can't wait, I'd expect what you describe to work.

**Comment by RafalLukawiecki** [comment]
Happy to wait. I was unsure if major updates required something more, perhaps related to the way your script has set things up. Glad to hear this can be done using the in-app updater. Thank you for your work once again, @danb35.

**Comment by xames81** [comment]
how i can check witch version i have installed? Thanks

**Comment by xames81** [comment]
Where is in-app updater? Thanks

**Comment by danb35** [comment]
The answer to both of your questions is "in the Nextcloud admin pages".  For further information, read the Nextcloud admin manual.

**Comment by xames81** [comment]
but i install over the script, not the nextcloud admin pages, i have to wait then to upgrade? thanks.

**Comment by xames81** [comment]
Ok thanks.
