### ISSUE TITLE
Caddy install broken

### ISSUE THREAD

**Issue by Ornias1993** [danb35/freenas-iocage-nextcloud#126]
Just for documentation sake:
Currently the Caddy install is broken, due to choices made by the upstream developer.

This basically breaks the script as-is.

**Comment by danb35** [comment]
Yep, see af25860419625e48afd1fb32ec9372e0f7f99ae0

**Comment by Ornias1993** [comment]
@danb35 Awesome, makes sure even people outside of the IX forum are aware of the issues...
