### ISSUE TITLE
Script does not respect "vnet_default_interface" parameter in config file

### ISSUE THREAD

**Issue by omid-1985** [danb35/freenas-iocage-nextcloud#143]
I'm running nextcloud jail in a separate em0 network interface (not VLAN, and not to be confused with INTERFACE or JAIL_INTERFACE parameters).
If I create jail manually and set vnet_default_interface to em0, everything does work, and it communicates with my DMZ network. However, since there is no vnet_default_interface parameter pull from config file, adding vnet_default_interface="em0" or vnet_default_interface=em0 in config file create a nextcloud jail with vnet_default_interface=auto and therefore script fails to communicate with DNS server.
![Screenshot from 2020-09-09 13-01-23](https://user-images.githubusercontent.com/19699810/92549565-e4764e80-f29c-11ea-90f8-bc30a786a336.png)
![Screenshot from 2020-09-09 13-00-36](https://user-images.githubusercontent.com/19699810/92549567-e5a77b80-f29c-11ea-8296-6a679bfa4961.png)

**Comment by omid-1985** [comment]
Fixed my issue by adding:
`vnet_default_interface="em0" dhcp="1"` at the end of `if ! iocage create --name "${JAIL_NAME}" -p /tmp/pkg.json -r "${RELEASE}" interfaces="${JAIL_INTERFACES}" ip4_addr="${INTERFACE}|${IP}/${NETMASK}" defaultrouter="${DEFAULT_GW_IP}" boot="on" host_hostname="${JAIL_NAME}" vnet="${VNET}" '
 `
Also added jail mac address on my DHCP server and reversed IP address same as what I entered in config.

**Comment by omid-1985** [comment]
Anyone who my above comments might mislead them, Please do not use the above method for putting DMZ NIC on your Freenas for security reasons!
Methods above will work, but it adds your DMZ nic in bridge0 next to the other interfaces which is at odds with the DMZ principle.
The correct method to have an isolated NIC for jails is to create new Bridge in your nextcloud interface (for example bridge22) with your separate NIC as a member. Then only use JAIL_INTERFACES parameter to assign it into your jail. For Example:
JAIL_INTERFACES="vnet0:bridge22"

**Comment by devinitnz** [comment]
I found this helpful, thank you. In my case I am using link aggregation, and VLANs. I found setting the vnet_default_interface="**none**" in the jail script and using JAIL_INTERFACES="vnet0:bridge22" in the nextcloud-config produced the results I needed.
Would be helpful if the "vnet_default_interface" was a configurable option.
