### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

### ISSUE THREAD

**Issue by adrido** [danb35/freenas-iocage-nextcloud#145]
Happens on a fresh installation of FreeNAS-11.3-U4.1

log and config attached.
nextcloud-config renamed to nextcloud-config.txt

steps to reproduce:

create new dataset nextcloud in DatenPool1
run the script.

```!log
...
* Starting nextcloud
  + Started OK
  + Using devfs_ruleset: 6
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Command: mysql -e CREATE DATABASE nextcloud; failed!
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
...
````

[nextcloud.log](https://github.com/danb35/freenas-iocage-nextcloud/files/5246519/nextcloud.log)
[nextcloud-config.txt](https://github.com/danb35/freenas-iocage-nextcloud/files/5246522/nextcloud-config.txt)

**Comment by danb35** [comment]
That makes it look like `mysql` isn't running.  What's the output, in the jail, of `service mysql status`?  And if it isn't running, `service mysql start`?

**Comment by adrido** [comment]
```
root@nextcloud:~ # service mysql status
mysql does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
root@nextcloud:~ #

root@nextcloud:~ # service mysql start
mysql does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
root@nextcloud:~ #
```

**Comment by adrido** [comment]
Reinstalled it today and now all works fine. 
Thank you for your script.
