### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bureaua24** [danb35/freenas-iocage-nextcloud#157]
I'm about to install your script.  I purchased a public domain at EasyDNS Domain provider.  Will caddy work with EasyDNS to obtain a TSL certificate?

Thank You

**Comment by danb35** [comment]
I missed this earlier.  Caddy will obtain a cert from ZeroSSL or Let's Encrypt.  If you need to use DNS validation for your cert, no, Caddy doesn't support them--they don't have a generally-available API for such use.  If that's a requirement, you may want to consider switching your DNS hosting to a provider like Cloudflare who does have such an API.
