### ISSUE TITLE
Connection refused after new installation on TrueNAS 12 / 12.2-RELEASE

### ISSUE THREAD

**Issue by Fenix4k** [danb35/freenas-iocage-nextcloud#159]
hello there

I have been using your scripts several times over the last few years and it always worked perfectly fine (unless I myself did something stupid or did read your instructions carefully ;)

this time, after re-reading everything several times and comparing to my old nextcloud-config file I don't know what to do

some information first: I recently update to TrueNAS 12 and therefore wanted to do a clean reinstall of nextcloud
iocage is using the 12.2 Release for creating jails

I prepared the config file as usual (NO_CERT=1 in my case, HOST_NAME="192.168.X.X as I did in previous installaions)

so after installation I tried to connect with the browser and the connection gets refused (ERR_CONNECTION_REFUSED)

the only thing so far that I've found that seem different than before is that the new nextcloud installation does not have a mount point for the portsnap folder on my TrueNAS ... I used the same location the previous installation was pointing to (as I think it is unrelated to Nextcloud)
adding the portsnap folder manually did not help

are there maybe any known problems with TrueNAS 12 or 12.2-RELEASE of iocage?

**Comment by theflyingsquirrel88** [comment]
I just did the installation and have the same issue.
I used cloudflare plugin for my cert though.
But I cannot even connect with internal ip address.
Did you find out what is wrong?

**Comment by ohohrobinho** [comment]
Same here.
If I look at the big chunk of text before it says it is complete, I cannot see anything that hints to an error.
When I try to to access the webpage (either through internal IP-address or the URL), (Chromium) Edge tell me it refused to connect.
If you need more info, please let me know.

**Comment by danb35** [comment]
> I just did the installation and have the same issue.

@theflyingsquirrel88, No, you don't.  You're getting a different error, with almost certainly a different cause.  Please open a separate issue.

@Fenix4k, connection refused almost always means Caddy isn't running.  That means either it never installed properly, or some error prevented it from starting.  To check for the first, take a careful look at `nextcloud.log` in the script's directory (or attach it here).  To check for the second, inside the jail, take a look at `/var/log/caddy.log`.

**Comment by Fenix4k** [comment]
hey dan

thanks for the tip, it was indeed caddy
as I used the IP as my host name as well, caddy set up the configuration file with the IP twice (instead of IP and the a 'real' host name) and therefore couldn't load the config

removing the IP once and it worked like a charm ...

sorry for the inconvenience and thanks again for your help!
also thanks for the awesome script ... as said I used it several times so far and it makes things go so much easier! :)
