### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR and ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by theflyingsquirrel88** [danb35/freenas-iocage-nextcloud#160]
I just install the NextCloud on TrueNAS-12.0-U1
DNS_cert with Cloudflare proxy.
DNS_PLUGIN=cloudflare
When the script is done, I cannot even connect with internal ip address.
If I open from internal ip of the jail, it shows
ERR_SSL_PROTOCOL_ERROR
If i open from domain address, it shows
ERR_TOO_MANY_REDIRECTS

**Comment by nikinsp** [comment]
Same for me:
If I open from internal ip of the jail, it shows
ERR_SSL_PROTOCOL_ERROR

**Comment by danb35** [comment]
Connecting by IP isn't supported when you have a cert, and Cloudflare's proxy can cause problems.  Disable it, and fix the DNS on your LAN so it points to the IP address of your jail.
