### ISSUE TITLE
Permission denied at starting the script (script nextcloud.log ./nextcloud-jail.sh)

### ISSUE THREAD

**Issue by vanDariu** [danb35/freenas-iocage-nextcloud#168]
Inexperienced user... Sorry...

At the EXECUTION stage, the script is stoping immediately with the message: „Permission denied”. I'm running a Truenas core as root, inside the built-in shell. I tried to find errors in the syntax, but I didn't notice any. Is this easily correctable?

**Comment by danb35** [comment]
Try `chmod +x nextcloud-jail.sh`, and then try again--I think I'm missing a permissions bit.

**Comment by vanDariu** [comment]
Yes, now it's working. Thank you!
