### ISSUE TITLE
Cannot reach server

### ISSUE THREAD

**Issue by vanDariu** [danb35/freenas-iocage-nextcloud#169]
I have tried many possible solutions, but I still cannot reach the server. I am pretty certain it is something regarding this line in the installation notes: "Also, HOST_NAME needs to resolve to your jail from inside your network. You'll probably need to configure this on your router. If you're unable to do so, you can edit the hosts file on your client computers to achieve this result.", but it seems I don't have enough experience to resolve the issue. Is here a solution?

**Comment by vanDariu** [comment]
The error I receive when It seems I do reach the server is: "write tcp 10.239.48.48:38485: write: connection refused"

**Comment by vanDariu** [comment]
It appears that in the Caddyfile in the usr/local/www folder there was a missing "#" before just "email" in line 4 I think (I had not entered an email during the instalation and just 'email' was wrong). With this being resolved, everything seems to be working fine. :) Thank you for this script and have a good day!

**Comment by danb35** [comment]
> I had not entered an email during the installation

Ah, that's a problem; you should have.  I thought I checked for that in the script.

**Comment by vanDariu** [comment]
Should I enter it anyway? Is there perhaps a problem if I don't enter it? In general, I try not to give it away too often if it's possible... Otherwise, the installation is working fine until now, thank you for your work!

**Comment by danb35** [comment]
Let's Encrypt encourages giving an email address--it's only used if your cert is about to expire (which shouldn't ever be the case) or if there are upcoming breaking changes to their system.  But it isn't mandatory to use the service.

**Comment by vanDariu** [comment]
Got it! Thank you very much!
