### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by jasegw** [danb35/freenas-iocage-nextcloud#171]
Righty,

I have been banging my head against the wall for a while, seen lloads of videos, read loads of docs, still no go.

So, I have a fresh install of TruNAS, with internal IP 10.10.1.200
No vLANS, Bridges etc. I can get to it from outside world no pro=blem. I can install and run the other script that sorts out the SSL via LetsEncrypt.

I followed this guide to the letter with no joy, so before I do it again, can ssomeone point me inthe right direction of how to setup so this script will work.

Thanks.

**Comment by danb35** [comment]
> I followed this guide to the letter with no joy

What exactly does this mean?  What error did you see?
