### ISSUE TITLE
Nextcloud GUI on jail stop working after restart (probably network vnet problem)

### ISSUE THREAD

**Issue by Zantag** [danb35/freenas-iocage-nextcloud#173]
Hi, i have Ttruenas 12 with nextcloud in jail... Everything was work fine until today.... after restart on truenas i cant access gui on the jail ip. I not even ping the jail ip. I can log to jail with command iocage console nextcloud from my truenas but from the jail i cant ping 8.8.8.8 so i think it is a network problem. Any ideas how to fix that?

**Comment by gt2416** [comment]
If you can't ping 8.8.8.8 its a network issue. Make sure you dont have any other jails using the same IP. On your router make sure nextcloud jail has a static IP with its MAC address.
