### ISSUE TITLE
Let's Encrypt Certificate expired - connection only via vpn

### ISSUE THREAD

**Issue by bub4** [danb35/freenas-iocage-nextcloud#174]
Hi @danb35 I really appreciate your work with this one as it enabled me to have NextCloud running on my TrueNAS. The installation worked out beautiful and I managed to get my setup running well. Meanwhile the Let's Encrypt certificate expired and I have no Idea how to renew it. I could use the certificate on MacOS by trusting it to make it work, but this is not possible with the iPhone, I'm afraid. I have a duckdns domain without any port forwarding on my router. I did the port forwarding only for the installation. I only connect via vpn meanwhile. Would be glad, if you could give me a hint on how to solve this.
Thanks so much!

**Comment by danb35** [comment]
> without any port forwarding on my router

This is your problem.  The Let's Encrypt validation servers need to be able to access your installation on port 80 to validate that you still have control over your domain, and without the ports forwarded, they aren't able to do that.

**Comment by bub4** [comment]
thank you for the immediate reply. So there is no way to issue the renewal manually by myself? Should I better use a self made certificate then (if possible)

**Comment by bub4** [comment]
okay - sorry for disturbing you. I enabled the port forwarding, restarted the jail and it works again. Thanks again for your support and script!! How can I cheer you a beer?!

**Comment by bub4** [comment]
Hi @danb35 the certificate expired again and I reopened the port forwarding and did a restart but this time it did not do the job. Can I trigger the jail with a command to fetch the re-certification? Thank you so much once again!
