### ISSUE TITLE
Script not installing Nextcloud

### ISSUE THREAD

**Issue by rockye64** [danb35/freenas-iocage-nextcloud#177]
I've completed all the prerequisite steps and ran the script, but it will not install the Nextcloud plug-in.  I tried installing the plugin myself, but the installation will not proceed because the "nextcloud" jail already exists.  I tried stopping and deleting the nextcloud jail and rerunning the Nextcloud plugin install, but it won't work because the jail IP address already exists.

I also tried rerunning the script, but that does not work either.

One other issue I'm having is understanding the exact syntax for executing the script.  The readme file says run "script nextcloud.log ./nextcloud-jail.sh", but the shell does not know what to do with "script nextcloud.log".  I removed this part and was able to run the script .

Any help would be greatly appreciated.

**Comment by danb35** [comment]
No, it doesn't install the plugin--it was never intended to, and I've never said otherwise.  But how did you determine that it didn't install Nextcloud?

**Comment by rockye64** [comment]
So I am confused because the readme file says "This script will create an iocage jail on FreeNAS 11.3 or TrueNAS CORE 12.0 with the latest release of Nextcloud 21, along with its dependencies."  It does create the jail, but I cannot connect to the IP address I included in the nextcloud-config file.  

The script reports that Nextcloud is downloaded and installed, but when I open the plugin page in TrueNAS, it does not show that it has installed.  I tried installing Nextcloud myself, then running the script, but the script removes Nextcloud.

What am I doing wrong?

**Comment by danb35** [comment]
> The script reports that Nextcloud is downloaded and installed, but when I open the plugin page in TrueNAS, it does not show that it has installed

This is as expected--again, this script has nothing to do with the plugin.

>  It does create the jail, but I cannot connect to the IP address I included in the nextcloud-config file.

What happens when you try?

**Comment by rockye64** [comment]
So should I install the Nextcloud plugin?  If so, do I install before or after I run the script?

When I to to access the IP address, I receive the following error:
This site can’t provide a secure connection192.168.1.199 sent an invalid response.

I also cannot access my domain.  It appears there is no connection between the DNS provider and my NAS because when I enter the domain name (rocknascloud.com) it brings up the stock easyDNS page indicating this domain name is registered and managed by easyDNS, but does not show my content.

**Comment by danb35** [comment]
> So should I install the Nextcloud plugin?

No.  This script has nothing to do with the plugin.  Do not use the plugin.  Forget the plugin.  This script replaces (and, IMNSHO, greatly improves on) the plugin.

>  This site can’t provide a secure connection192.168.1.199 sent an invalid response.

That sounds like it's working normally, at least as far as you've shown.  You need to get the domain name working; the configuration this script produces won't ordinarily let you access the system by IP address.

>  It appears there is no connection between the DNS provider and my NAS because when I enter the domain name (rocknascloud.com) it brings up the stock easyDNS page indicating this domain name is registered and managed by easyDNS, but does not show my content.

That sounds like you need to add proper DNS records.

**Comment by rockye64** [comment]
Ok - thank you!  When you say, "you need to add proper DNS records", is that on my router on elsewhere.  I followed all the steps in your readme, so i'm not sure what i need to fix to make this work.

**Comment by danb35** [comment]
>  I followed all the steps in your readme,

I don't think you did:
![image](https://user-images.githubusercontent.com/12121759/125337649-43717d80-e31d-11eb-8704-061f12e64b95.png)

As to this:
> "you need to add proper DNS records", is that on my router on elsewhere. 

It really depends on whether you intend to access your Nextcloud installation from outside your LAN.  If so, you'll need appropriate DNS records at your DNS host (likely EasyDNS).  If not, you don't really need to do anything there; you could set them on your router or whatever other device is providing DNS for your LAN.
