### ISSUE TITLE
Cron Task Issue

### ISSUE THREAD

**Issue by arthertm** [danb35/freenas-iocage-nextcloud#178]
Hi, firstly to say this is not an issue with your script which I've found to be flawless, thank you, but an issue that has emerged (i believe) since update to stable 21.0.3.  I get the error "Last background job execution ran 24 days ago. Something appears wrong."  Something has changed as this worked perfectly before but wondering if you could give me any pointers as to what may change changed/resolve? thank you

**Comment by danb35** [comment]
In the jail, check the command that's being run with `crontab -u www -l`.  Then try to run it from the shell prompt and note any errors.

**Comment by arthertm** [comment]
Thanks Dan.

This is the response with -l

*/5 * * * * /usr/local/bin/php -f /usr/local/www/nextcloud/cron.php

Sorry for being somewhat dim... how do I manually run the task from shell?

Thank you

**Comment by danb35** [comment]
The command starts with the `/usr`, so run `/usr/local/bin/php -f /usr/local/www/nextcloud/cron.php`

**Comment by arthertm** [comment]
Thanks for fast response Dan. 
I ran the above command in the Nextcloud Jail "/usr/local/bin/php -f /usr/local/www/nextcloud/cron.php" and did not get any error messages.  I logged back into Nextcloud and the same error is there "Last background job execution ran 24 days ago. Something seems wrong. Check the background job settings"
Thanks

**Comment by arthertm** [comment]
Dan, apologies - tried that again, not sure what I was looking at before, I get the following error: 

"Could not open input file: /usr/local/www/nexcloud/cron.php"

**Comment by arthertm** [comment]
Any further ideas on this please? Error still persists. thank you

**Comment by arthertm** [comment]
Thank you - I run the command and get no errors, however Nextcloud still states "Last background job execution ran last month. Something seems wrong. Check the background job settings".  Is their any further diagnosis you can recommend please? Again, I can only conclude this error appeared after minor upgrade to latest stable version (21.0.3). Any help appreciated.

**Comment by t26y** [comment]
I think I fixed it: I noticed an error about apcu not being available when trying to set an unrelated config variable from the command line.

Some googling then led me to **enable apc for the cli** by setting `apc.enable_cli=1` in `/usr/local/etc/php.ini`., as mentioned here: https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/caching_configuration.html#id1
This also appears to have fixed the cron issue.
