### ISSUE TITLE
/.well-known/webfinger & /.well-known/nodeinfo

### ISSUE THREAD

**Issue by Bosstox** [danb35/freenas-iocage-nextcloud#179]
Hi. 

I installed the nextcloud with your script in 2019. 

After updating my nextcloud to 21 i got the error from above. I was searching for long time for a fix but can't find one that is working. 
The nextcloud is running on Caddy V1. Your new script and files are for Caddy V2.

I added the lines in the Caddyfile for the two well-known but this doesn't fix it. 

Is there a way to update the Caddy from V1 to V2 or is it easier to make a clean installation?

thx

**Comment by danb35** [comment]
> Is there a way to update the Caddy from V1 to V2 or is it easier to make a clean installation?

It's probably easier to just do a clean installation.  To be on the safe side, stop your current jail, and when you re-run the current version of the script, change the jail name.  Also, snapshot wherever you're storing all your Nextcloud data.  That way, if it all goes sideways, you can roll back to the snapshot and reuse the old jail.

**Comment by Bosstox** [comment]
thx.

will do it as soon as i have time for that.
