### ISSUE TITLE
 Cron Task Issue?  

### ISSUE THREAD

**Issue by arthertm** [danb35/freenas-iocage-nextcloud#183]
Hi Dan,

I recently did a fresh install of 23, to update from 22 (choose a fresh install).  All is good except for the Nextcloud background tasks dont run, I get a "Last job execution ran 12 minutes ago. Something seems wrong" message.

_crontab -u www_ -e shows 

_*/5 * * * * /usr/local/bin/php -f /usr/local/www/nextcloud/cron.php_

which looks correct.. but something amiss.. 

Is their anything you can suggest? It would appear as though the task is not running.  

Any guideance appreciated.

**Comment by danb35** [comment]
What happens if you try running `/usr/local/bin/php -f /usr/local/www/nextcloud/cron.php` manually from within the jail?  Does that change anything?

**Comment by arthertm** [comment]
Thanks or coming back Dan, response to that is..

Console has to be executed with the user that owns the file config/config.php
Current user id: 0
Owner id of config.php: 80

**Comment by arthertm** [comment]
Any ideas please? thank you

**Comment by dlauper** [comment]
I can confirm the error of @arthertm, I see the same error message when running the cron.php. It also shows up whenever I run the occ command for any action. 

Which also already happened during the installation process, exactly at the occ set memcache APCu line (490). After that, the error shows up for the remaining occ commands. Here is an extract of the installation process:
```
The current PHP memory limit is below the recommended value of 512MB.
System config value log_type set to string file
The current PHP memory limit is below the recommended value of 512MB.
System config value logfile set to string /var/log/nextcloud/nextcloud.log
The current PHP memory limit is below the recommended value of 512MB.
System config value loglevel set to string 2
The current PHP memory limit is below the recommended value of 512MB.
System config value logrotate_size set to string 104847600
The current PHP memory limit is below the recommended value of 512MB.
System config value memcache.local set to string \OC\Memcache\APCu
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set redis host --value="/var/run/redis/redis.sock" failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set redis port --value=0 --type=integer failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set memcache.distributed --value="\OC\Memcache\Redis" failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set memcache.locking --value="\OC\Memcache\Redis" failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set overwritehost --value="myhostname.net" failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set overwrite.cli.url --value="http://myhostname.net" failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set overwriteprotocol --value="http" failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set htaccess.RewriteBase --value="/" failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ maintenance:update:htaccess failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set trusted_domains 1 --value="myhostname.net" failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ config:system:set trusted_domains 2 --value="192.168.0.251" failed!
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
Command: su -m www -c php /usr/local/www/nextcloud/occ background:cron failed!
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)

Command: su -m www -c php -f /usr/local/www/nextcloud/cron.php failed!
crontab: /mnt/includes/www-crontab: Permission denied
Command: crontab /mnt/includes/www-crontab failed!
Successfully removed mount from nextcloud_23's fstab
Installation complete!
```

Researching this error quickly leads to php.ini, where the following line is needed (`apc.enable_cli=1`), but this is already correct.

**Comment by GJSchaller** [comment]
I came here to note something similar, in that when i run tasks from the command line / shell inside the Jail, it does not seem to pick up settings from php.ini - in my case, I both noted that apc.enable_cli=1 was set (and ignored by the CRON task), but also that it didn't seem to honor the memory limit of 512MB from the command line when running a manual update of Nextcloud.

Is it possible the command line version of PHP is not pulling from the same php.ini, or something similar?

**Comment by GJSchaller** [comment]
I've been doing some troubleshooting on the PHP side - the ini file seems to be honored from the command line when running basic diagnostics (php --ini outputs the desired variables / settings: memory_limit is 512M ).  Maybe the issue is linked a setting within the Nextcloud file structure / environment?

**Comment by GJSchaller** [comment]
The permissions on php.ini are incorrect, resulting in the user www not being able to read it, and applying the defaults.  Here's the discussion:

https://forums.freebsd.org/threads/php-8-0-command-line-ignoring-php-ini-in-freebsd-13-1-jail.85320/

I did a chmod 644 to my php.ini, and things are now working properly.

**Comment by danb35** [comment]
@GJSchaller, thanks for tracking down the issue--I never saw it myself, so I'm not sure why you (and others) were having this problem, but that gave me something to work with.  I've addressed in the script by changing ownership on `php.ini` rather than changing its permissions.
