### ISSUE TITLE
unable to build quic-go

### ISSUE THREAD

**Issue by toniglandy1** [danb35/freenas-iocage-nextcloud#187]
as of 11th of April 2022, running the script as-is on truenas 12.0-U8 brings a build fail on caddy without plugins. This is due to the script trying to build quick-go 0.23.0 which doesn't build on later versions of go. You need to change the build command to use the latest version :

`iocage exec "${JAIL_NAME}" xcaddy build --output /usr/local/bin/caddy  --with github.com/lucas-clemente/quic-go@latest`

**Comment by danb35** [comment]
This should be resolved now with the release of Caddy 2.5.0.
