### ISSUE TITLE
"Reverse proxy header configuration is incorrect" message in admin overview

### ISSUE THREAD

**Issue by danb35** [danb35/freenas-iocage-nextcloud#189]
See:
https://help.nextcloud.com/t/the-reverse-proxy-header-configuration-is-incorrect-or-you-are-accessing-nextcloud-from-a-trusted-proxy/139286

**Comment by redr00t** [comment]
same problem here

**Comment by danb35** [comment]
This is an upstream problem that nobody at Nextcloud seems to be interested in looking into.

**Comment by redr00t** [comment]
if I write anything (like asdasdasdasdasd) in "trusted_proxy" the error disappears, however that does not give me peace of mind, what do you think? should i not use caddy as webserver (with nextcloud)?

**Comment by NasKar2** [comment]
I added these lines to my config.php and it fixed the error. 192.168.5.81 is my caddy reverse proxy jail IP
`  'trusted_proxies' =>
  array (
    0 => '192.168.5.81',
    1 => 'localhost',
    2 => 'cloud.mydomain.com',
    3 => '::1',
  ),`
