### ISSUE TITLE
Got the HSTS message with self signed cert

### ISSUE THREAD

**Issue by sfatula** [danb35/freenas-iocage-nextcloud#193]
Tried to follow your instructions to remove the comment for Strict-Transport-Security in the Caddyfile, but, for the self signed Caddyfile, there is no such line! So, I copied the 4 lines from a different Caddyfile and the warning now goes away.

Shouldn't those lines be in the self signed Caddyfile?

**Comment by danb35** [comment]
Why would you want HSTS enabled with a self-signed certificate?
