### ISSUE TITLE
File upload limit is limited to 10Mb

### ISSUE THREAD

**Issue by EhabKan** [danb35/freenas-iocage-nextcloud#194]
how can I increase it, as I am using next clous to share huge files,

**Comment by danb35** [comment]
The stock installation allows uploading of files through the Nextcloud web UI or through client software of at least 10 GB, tested repeatedly on my systems.  Where are you seeing a limit of 10 MB?

**Comment by EhabKan** [comment]
I cannot upload bigger than 10mb, I don't know why, Could you Please Please help me,

**Comment by EhabKan** [comment]
I have installed it by your script, matched every aspect, and it worked like a Charm, but only the upload size limit :(

**Comment by EhabKan** [comment]
BTW, the limitation is not there with the ios app.

**Comment by danb35** [comment]
So where do you see the limitation?  What happens when you try to upload a larger file?

**Comment by EhabKan** [comment]
just nothing, 
- drag and drop "no reaction, like if you didn't drop a file".
- the plus icon the same,
btw, I can give you a "google remote control over my windows pc with truenas logged in and the nextcloud, for further investigations" if you wanna check by yourself.

**Comment by danb35** [comment]
Drag and drop what?  Where?  What plus icon?  Keep in mind, I'm not telepathic, and I'm not going to log in to your machine--I need you to describe, in detail, what's going on.

**Comment by EhabKan** [comment]
If you want to upload a file in the web Ui, you have to drag and drop this file or use the plus icon (in the small circle).. I guess this is the only two ways to upload a file in the web ui, when you are trying to upload a file larger than 10mb, it will just ignore your request. any small file will just upload normally. the same on my iphone if I am using the web ui, but it is not happenning If I am using the mobile app. the app works great. this issue happened to me months ago with my old nas it was due to Nginx max body size, but in your script I guess you are using Caddy, I have tried my best to edit Caddyfile to make it accept bigger files with no success.

**Comment by EhabKan** [comment]
Knew the reason. I have had the ACL permissions of the dataset "files" with the user "not www".. Sorry. fixed it.
