### ISSUE TITLE
autostart on boot,

### ISSUE THREAD

**Issue by EhabKan** [danb35/freenas-iocage-nextcloud#195]
the nextcloud jail is not autostarting on truenas boot. it's starting normally when I press start on the jails GUI in truenas but not auto starting,
note: the jail setting is set to Boot: on

Thought about creating an init script from Init/shutdown scripts from truenas Tasks to start it on boot by putting this command "/etc/rc.d/jail onestart nextcloud"
but it didn't start giving me this:
"Starting jails: /etc/rc.d/jail: WARNING: Invalid configuration for nextcloud (no jail.conf, no hostname, or no path). Jail nextcloud was ignored."

**Comment by danb35** [comment]
That sounds like a bug in TrueNAS; suggest you report it at https://ixsystems.atlassian.net/jira/
