### ISSUE TITLE
Installation debugging.

### ISSUE THREAD

**Issue by borats** [danb35/freenas-iocage-nextcloud#196]
:wave: 

Long time Linux user here but only use TrueNAS ocassionally and even more rarely need to jump to cmdline.

- Do `set -x` at the top of the install script for debugging.
- Ensure, `iocage install -r 12.3-RELEASE` before hand or whichever release is currently present at the time you read this post.
- If you have another iocage called nextcloud, ensure it is moved or deleted elsewhere.
- I found the 1 dataset with 4 sub-dataset is the simplest option. Head over to "Storage > Pools > Three dots ...".

It would be good if the shell script was a bit ~robust~ intuitive - I had prior experience debugging shell scripts (done it for long enough) and therefore, this debugging took me _maybe_ 10-20 minutes but I'd imagine it taking much longer for someone wrangling their way around debugging the script:) 

Lastly, thanks for this script (it gets the job done). I appreciate the time you put into it and sorry I don't use forums and such but thought this might help others.

The web-based TrueNAS installer can go to hell. It's a piece of crap.

**Comment by danb35** [comment]
Resolved by https://github.com/danb35/freenas-iocage-nextcloud/commit/7128c3604e97f4d146ee40c1c4d738cfaf54fbff
