### ISSUE TITLE
Redis issue on reinstall

### ISSUE THREAD

**Issue by tschettervictor** [danb35/freenas-iocage-nextcloud#198]
Lines 482-484 don’t run on a reinstall of this script. The commands are below.
When doing a reinstall there is a persistent 500 error. 

When running these two commands manually from the jail, and restarting it, Nextcloud starts working.

`# Add the www user to the redis group to allow it to access the socket`

`iocage exec "${JAIL_NAME}" pw usermod www -G redis`

`iocage exec "${JAIL_NAME}" chmod 777 /var/run/redis/redis.sock `

**Comment by danb35** [comment]
Fixed in #199
