### ISSUE TITLE
Cant access nextcloud via web after running script

### ISSUE THREAD

**Issue by crashbash2020** [danb35/freenas-iocage-nextcloud#202]
Hi, thanks for making this script for us noobs to use.

I'm having some trouble getting the script to work. It appears to run correctly, but when I navigate to my jail i.p. on my webpage i get "unable to connect" like nextcloud isnt actually running.

I'm running a freshly upgraded version of truenas 13.
```
 service nextcloud status
````
gives

```
nextcloud does not exist in /etc/rc.d or the local startup directories (/usr/local/etc/rc.d), or is not executable
```

my config settings were

```
JAIL_IP="192.168.20.220"
DEFAULT_GW_IP="192.168.20.1"
POOL_PATH="/mnt/WD3TB_RAIDZ2_VOL1/applicationData"
TIME_ZONE="Pacific/Auckland"
HOST_NAME="192.168.20.220"
NO_CERT=1
COUNTRY_CODE="NZ"

```

Only factors I wasn't sure about was the hostname, I dont use hostname usually for this kind of stuff just direct IP. I only need the service for internal network so no cert required.
(also whats the deal with the ports directory? isn't that deprecated now? i just left it blank as default)

cheers for any advice. Logfile is attached, not too worried about leaking passwords as I will run from scratch once i figure out what I'm doing wrong.

[nextcloud.log](https://github.com/danb35/freenas-iocage-nextcloud/files/11360726/nextcloud.log)

**Comment by danb35** [comment]
Well, simple stuff first: Nextcloud isn't a service that would be running; it's a web application, so you'd want to see if the web server is running: `service caddy status`.  And you'd run that in the jail, of course.  If it isn't running, perhaps its log file will help explain why; it's in `/var/log/caddy/caddy.log`.

**Comment by crashbash2020** [comment]
Hi thanks for the suggestion, I tried that as Im replacing an old broken nextcloud installation from my upgrade from 9.x. and that was how i checked it previously

Seems to actually be working now, not sure what i changed or if it was working all along and i was doing something dumb
