### ISSUE TITLE
Failed to install Nextcloud 

### ISSUE THREAD

**Issue by Azsumbre** [danb35/freenas-iocage-nextcloud#206]
Getting issue when trying to install nextcloud:
+ echo 'MariaDB root password is 076xehOuDnY3Zs6FNY8MTA=='
+ echo 'Nextcloud database password is rh3Lov78TKgvsLdWFKDERQ=='
+ echo 'Nextcloud Administrator password is E8efd8XSSN9eqIHI'
+ iocage exec nextcloud mkdir -p /var/log/nextcloud/
+ iocage exec nextcloud chown www:www /var/log/nextcloud
+ [ mariadb '=' mariadb ]
+ iocage exec nextcloud su -m www -c 'php /usr/local/www/nextcloud/occ maintenance:install --database="mysql" --database-name="nextcloud" --database-user="nextcloud" --database-pass="rh3Lov78TKgvsLdWFKDERQ==" --database-host="localhost:/var/run/mysql/mysql.sock" --admin-user="admin" --admin-pass="E8efd8XSSN9eqIHI" --data-dir="/mnt/files"'
ld-elf.so.1: /usr/local/lib/libtasn1.so.6: Undefined symbol "strverscmp@FBSD_1.7"
Command: su -m www -c php /usr/local/www/nextcloud/occ maintenance:install --database="mysql" --database-name="nextcloud" --database-user="nextcloud" --database-pass="rh3Lov78TKgvsLdWFKDERQ==" --database-host="localhost:/var/run/mysql/mysql.sock" --admin-user="admin" --admin-pass="E8

After this the script exits with Nextcloud failed to be installed

**Comment by cas206** [comment]
Tried latest version and got the same error.

**Comment by cas206** [comment]
Running that last line manually gives 
jail 'su' not found!

**Comment by cas206** [comment]
ld-elf.so.1: /usr/local/lib/libtasn1.so.6: Undefined symbol "strverscmp@FBSD_1.7"

**Comment by Azsumbre** [comment]
Tried to install it again today and used DATABASE="pgsql" instead of the default.
But still got the same error :
+ iocage exec nextcloud2p su -m www -c 'php /usr/local/www/nextcloud/occ maintenance:install --database="pgsql" --database-name="nextcloud" --database-user="nextcloud" --database-pass="ZPZRqOVlsRMsoknTD6zGQA==" --database-host="localhost:/tmp/.s.PGSQL.5432" --admin-user="admin" --admin-pass="QQgvgqI/Yq+1hRnr" --data-dir="/mnt/files"'
ld-elf.so.1: /usr/local/lib/libtasn1.so.6: Undefined symbol "strverscmp@FBSD_1.7"
Command: su -m www -c php /usr/local/www/nextcloud/occ maintenance:install --database="pgsql" --database-name="nextcloud" --database-user="nextcloud" --database-pass="ZPZRqOVlsRMsoknTD6zGQA==" --database-host="localhost:/tmp/.s.PGSQL.5432"--admin-user="admin" --admin-pass="QQgvgqI/Yq




EATE ROLE
+ iocage exec nextcloud2p psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASEnextcloud TO nextcloud;'
GRANT
+ iocage exec nextcloud2p psql -U postgres -c 'SELECT pg_reload_conf();'
 pg_reload_conf
----------------
 t
(1 row)

+ echo 'PostgreSQL root password is E68C4JCprKWpaBgOKTLGXw=='
+ echo 'Nextcloud database password is ZPZRqOVlsRMsoknTD6zGQA=='
+ echo 'Nextcloud Administrator password is QQgvgqI/Yq+1hRnr'
+ iocage exec nextcloud2p mkdir -p /var/log/nextcloud/
+ iocage exec nextcloud2p chown www:www /var/log/nextcloud
+ [ pgsql '=' mariadb ]
+ [ pgsql '=' pgsql ]
+ iocage exec nextcloud2p su -m www -c 'php /usr/local/www/nextcloud/occ maintenance:install --database="pgsql" --database-name="nextcloud" --database-user="nextcloud" --database-pass="ZPZRqOVlsRMsoknTD6zGQA==" --database-host="localhost:/tmp/.s.PGSQL.5432" --admin-user="admin" --admin-pass="QQgvgqI/Yq+1hRnr" --data-dir="/mnt/files"'
ld-elf.so.1: /usr/local/lib/libtasn1.so.6: Undefined symbol "strverscmp@FBSD_1.7"
Command: su -m www -c php /usr/local/www/nextcloud/occ maintenance:install --database="pgsql" --database-name="nextcloud" --database-user="nextcloud" --database-pass="ZPZRqOVlsRMsoknTD6zGQA==" --database-host="localhost:/tmp/.s.PGSQL.5432"--admin-user="admin" --admin-pass="QQgvgqI/Yq+1hRnr" --data-dir="/mnt/files" failed!
+ echo 'Failed to install Nextcloud, aborting'
Failed to install Nextcloud, aborting
+ exit 1

Also tried it on TrueNas U5.3 and U1.1 , but still the same issue

**Comment by Azsumbre** [comment]
Can someone help?

**Comment by normanoffel** [comment]
I don't have the problem but would be interested in the solution.
https://forums.freebsd.org/threads/version-fbsd_1-7-required-by-usr-local-lib-libpython3-9-so-1-0.86449/ suggests that you may need to update your system but you already have the newest version U5.3. But it also says that the jails need to be updated, too. Did you check the jail version as well? I'm not experienced in FreeBSD at all, but I think this could only occur if you reinstall via the script instead of a fresh installation since that would always use the newest version available for the OS, I assume.

**Comment by danb35** [comment]
I don't know that I can help immediately, but I'm getting the same error.  `libtasn1.so.6` appears to belong to the GnuTLS, and the error appears to suggest that it wasn't compiled correctly for this version of FreeBSD.

**Comment by tschettervictor** [comment]
Workaround right now is to edit the `nextcloud-jail.sh` file, comment out the `RELEASE` line (I think it’s 20-30 lines into the script) and add another line underneath it like this.

`RELEASE=“13.2-RELEASE”`

Just tried and it worked.

**Comment by danb35** [comment]
I'd suspected the same and was in the middle of testing it, but seems you beat me to it.  The combination of hyper-aggressive EOL policies by the FreeBSD crew and iX' inability to keep their underlying OS up-to-date strikes again.

**Comment by tschettervictor** [comment]
I sure hope they don’t stop at 13. It would sure not be very helpful if things would break because of the underlying OS lagging behind.

Especially TrueNAS Core, the playground of FreeBSD imo.

**Comment by tschettervictor** [comment]
Should probably add that to the script ASAP because people generally don't read the issues before trying to install. Unless that would conflict with installing on a regular FreeBSD system.

**Comment by Azsumbre** [comment]
Checked it , it works
