### ISSUE TITLE
download.htm "site wasn't available" when downloading a folder

### ISSUE THREAD

**Issue by raffskid** [danb35/freenas-iocage-nextcloud#216]
Hello,

I am running Nextcloud version 28.0.2 with Truenas version 13.0-U6.1. Let me know if you need more information.

When I attempt to download a folder as a zip file, it instead attempts to download a file called "download.htm" and errors out with "site wasn't available". Single files work just fine. 

I saw that this was added as a bug on the nextcloud github page for a docker image, and it was fixed by editing a line in the nginx.conf file: https://github.com/nextcloud/server/issues/42617#issuecomment-1881958718

I, however, cannot find this configuration file anywhere. The Nextcloud admin manual says it is in /var/www/nextcloud, but I can't seem to find that directory. Googling this also came up with no results as it seems most people who run Nextcloud do not run it on Truenas. Any ideas on how to fix?

![image](https://github.com/danb35/freenas-iocage-nextcloud/assets/110488465/66e8ec12-87fa-4577-98c9-59805530bd1d)

**Comment by danb35** [comment]
> I, however, cannot find this configuration file anywhere. 

That isn't surprising, as my script doesn't use nginx; it instead uses Caddy as its web server, and its config file is in `/usr/local/www/Caddyfile`.  That also means the rewrite line would need to be changed to match Caddy syntax.

**Comment by Gblenn** [comment]
Great, someone else with the same issue I'm having... So what would that look like in Caddyfile?

The suggested correction for Nginx is: 
# Required for legacy support
        rewrite ^/(?!index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|ocs-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;

**Comment by tschettervictor** [comment]
Give this block a try and see if it works.

```
@notlegacy {
                path *.php
                not path /index*
                not path /remote*
                not path /public*
                not path /cron*
                not path /core/ajax/update*
                not path /status*
                not path /ocs/v1*
                not path /ocs/v2*
                not path /ocs-provider/*
                not path /updater/*
                not path */richdocumentscode/proxy*
        }
        rewrite @notlegacy /index.php{uri}
```
