### ISSUE TITLE
mariadb update

### ISSUE THREAD

**Issue by matowa** [danb35/freenas-iocage-nextcloud#35]
First, please note that I'm not an experienced contributor. However, I want to give it a try.

I believe the mariadb101-server pkg has been upgraded to mariadb102-server at least with my freenas -U4 version and the original mariadb101-server pkg isn't included in the pkg-list anymore.

After having changed the list of pkg to be installed in the script the installation of mariadb works smooth. However, the commands for creating the database fail because of some user privilege issues. Mariadb introduced a new handling of "mysql -u root" and there exist new commands in this context like "ALTER USER".

I somehow managed to get nextcloud running by logging into the mariadb interface and then more or less adjusting the database creation commands. However, I believe someone else will better know what he/she is doing.

Hope this helps.

**Comment by danb35** [comment]
There's a thread on the FreeNAS forums about this: https://forums.freenas.org/index.php?threads/cant-install-mariadb101-server-in-iocage-jail.63816/

From that thread, it sounds like mariadb101-server was MIA for a little while, but is now back in the repos.  I'm able to run the script as is and install mariadb101-server (it's running right now), so I don't think an upgrade to 10.2 is needed in the short term.

**Comment by bryanberger** [comment]
I upgraded to 102, all works fine.

**Comment by jbddc** [comment]
I ran the script today and got this:

`- mariadb101-server...
pkg: http://pkg.FreeBSD.org/FreeBSD:11:amd64/quarterly/All/mariadb101-server-10.1.35_1.txz: Operation timed out`

**Comment by danb35** [comment]
Latest commits (responding to #61) upgrade to MariaDB 10.3.
