### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Sonrio224** [danb35/freenas-iocage-nextcloud#47]
I am unable to access nextcloud and I honestly don't know what to do. 
I saw under the issues that someone had a similar problem and fixing it was under the nextcloud config.php

but this didn't fix my issue. here is the log file, [https://drive.google.com/open?id=1Pb3UNVHeLI-AZC2UU62kc4gI4gZFL1B8](url),  i wanted to paste it here but the output is like... holy cow there is a lot.

One thing i see a lot in the log file is, "Is the matching PHP module installed and enabled?"

I don't know what this means and i would like some help. please!

**Comment by hanwellr** [comment]
I found a fix by removing the memcatch. 
go 
vi /usr/local/www/apache24/data/nextcloud/config/config.php

and remove the line 

'memcache.local' => '\OC\Memcache\APCu',

this is just a workaround and i'm testing for a fix. 

tried with Redis 

'memcache.local' => '\OC\Memcache\Redis',

Didn't work. so there is an issue with the memcatching 

https://docs.nextcloud.com/server/13/admin_manual/configuration_server/caching_configuration.html

**Comment by Sonrio224** [comment]
Sorry for the late response.

Yea that did fix my issue. has this always been a problem or am I the odd one out?

**Comment by hanwellr** [comment]
Glad it fixed it for you. I think this is next cloud 14 not 13. They might have changed the memory catch or a mod didn't install. When I get time I'll check the package install. Nextcloud have a section on how this should work. Once fix I'll figure out how to update the script.

**Comment by tong2200** [comment]
pkg install php72-pecl-APCu
