### ISSUE TITLE
No config.php

### ISSUE THREAD

**Issue by Judoguy12** [danb35/freenas-iocage-nextcloud#57]
Hi there I have no way of finding the nextcloud config now it is installed and can access the web interface for both nextcloud and FreeNAS separately but can’t find a way to enable the noip service

Any help thanks.

**Comment by danb35** [comment]
I'm not aware of Nextcloud supporting noip at all, but the config file is at `/usr/local/www/apache24/data/nextcloud/config/config.php`.
