### ISSUE TITLE
First time logging into Nextcloud after install is complete

### ISSUE THREAD

**Issue by cage4000** [danb35/freenas-iocage-nextcloud#59]
I apologize if this is a complete nub question but i need to know what to put into the "Configure the database" the first time i pull up my nextcloud site.  What ever i try i can not get past this screen.  I used the txt file that gave me the MariaDB root password, the Nextcloud database password, and the Nextcloud Administrator password, but every combination that i use do not get me in.

Database user  ---?
Database password---?
Database name---?
Database host---?

Bare in mind i used the following as my nextcloud-config:

JAIL_IP="10.0.0.15"
DEFAULT_GW_IP="10.0.0.1"
INTERFACE="re0"
VNET="off"
POOL_PATH="/mnt/tank"
JAIL_NAME="nextcloud"
TIME_ZONE="America/Los_Angeles" # See http://php.net/manual/en/timezones.php
HOST_NAME="***.com" # not my real website
DATABASE="mariadb"
STANDALONE_CERT=0
DNS_CERT=0
SELFSIGNED_CERT=0
NO_CERT=1
TEST_CERT=""

![chrome_2019-03-20_13-27-19](https://user-images.githubusercontent.com/48772290/54716852-f6e25280-4b13-11e9-9c80-67bf3d100f88.png)

Any help would be greatly really appreciated.

**Comment by danb35** [comment]
Nope, not a n00b question.  You shouldn't be seeing this; the script should configure everything appropriately.  The database user and name should both be "nextcloud", and the password is the Nextcloud database password.  The host is localhost.

From the FreeNAS shell, what's the output of `iocage fstab -l nextcloud`?

**Comment by cage4000** [comment]
thank you danb35 for the clarification.  here is what the iocage shows:

root@freenas:/ # iocage fstab -l nextcloud
+-------+--------------------------------------------------------------------------------------+
| INDEX |                                     FSTAB ENTRY                                      |
+=======+======================================================================================+
| 0     | /mnt/tank/portsnap/ports /mnt/iocage/jails/nextcloud/root/usr/ports nullfs rw 0 0    |
+-------+--------------------------------------------------------------------------------------+
| 1     | /mnt/tank/portsnap/db /mnt/iocage/jails/nextcloud/root/var/db/portsnap nullfs rw 0 0 |
+-------+--------------------------------------------------------------------------------------+
| 2     | /mnt/tank/files /mnt/iocage/jails/nextcloud/root/mnt/files nullfs rw 0 0             |
+-------+--------------------------------------------------------------------------------------+
| 3     | /mnt/tank/db /mnt/iocage/jails/nextcloud/root/var/db/mysql nullfs rw 0 0             |
+-------+--------------------------------------------------------------------------------------+

**Comment by cage4000** [comment]
Also, if it helps trouble shoot this issue, the version of Freenas that i'm running is: FreeNAS-11.1-U7

**Comment by TimvHerpen** [comment]
> Also, if it helps trouble shoot this issue, the version of Freenas that i'm running is: FreeNAS-11.1-U7

I don't know if you're still trying to make it work, but this script is not supported on 11.1 since the package sources are outdated. You could use ports to install the packages and it'll probably work, but best practice is to use 11.2(although they have their own bugs).

**Comment by Ornias1993** [comment]
@danb35 This can be closed.
Said issues have long been solved and the FreeNAS and Nextcloud versions involved are not even supported by this script anymore...
