### ISSUE TITLE
Adding 4-byte support to SQL DBMS [REQUEST]

### ISSUE THREAD

**Issue by Jacopx** [danb35/freenas-iocage-nextcloud#61]
The new version of Nextcloud 15.0.6 require, to pass all the test, the support for 4-byte characters for emoji and other stuffs. 
Here the [Nextcloud support](https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html) related!

**Comment by danb35** [comment]
See if the latest commit addresses this--it seems to cover what's recommended in the docs, and I don't see any warnings about it.

**Comment by Jacopx** [comment]
Perfectly achieved!
