### ISSUE TITLE
Cant't upload lager files

### ISSUE THREAD

**Issue by Bosstox** [danb35/freenas-iocage-nextcloud#63]
Hi Folks. I'm new to this so i would need some help. I always get a fatal error when uploading lager files. Uploading Photos, Mp3 and so small files work. Max Filesize is set to 5 GB. It is impossible to upload a file over the browser or the client.

Fatal | webdav | Sabre\DAV\Exception\BadRequest: expected filesize 100000000 got 64389120 |   | 2019-04-25T12:56:56+0200
-- | -- | -- | -- | --
Error | no app in context | Sabre\DAV\Exception\BadRequest: expected filesize 100000000 got 64389120 |   | 2019-04-25T12:56:56+0200
Fatal | webdav | Sabre\DAV\Exception\BadRequest: expected filesize 100000000 got 73121792 |   | 2019-04-25T12:56:36+0200
Error | no app in context | Sabre\DAV\Exception\BadRequest: expected filesize 100000000 got 73121792 |   | 2019-04-25T12:56:36+0200
Error | PHP | unlink(/mnt/files/appdata_ocvb538qn4em/css/core/3108-812e-css-variables.css): No such file or directory at /usr/local/www/apache24/data/nextcloud/lib/private/Files/Storage/Local.php#227 |   | 2019-04-25T12:50:41+0200
Fatal | webdav | Sabre\DAV\Exception\BadRequest: expected filesize 100000000 got 7110656 |   | 2019-04-25T12:38:43+0200
Error | no app in context | Sabre\DAV\Exception\BadRequest: expected filesize 100000000 got 7110656 |   | 2019-04-25T12:38:43+0200
Fatal | webdav | Sabre\DAV\Exception\BadRequest: expected filesize 100000000 got 19480576 |   | 2019-04-25T12:38:26+0200
Error | no app in context | Sabre\DAV\Exception\BadRequest: expected filesize 100000000 got 19480576 |   | 2019-04-25T12:38:26+0200

i tried to fix this using google but i don't get it working. Tried to create a new jail with a new installation same problem. 

I'm running FreeNAS-11.2-U3.

I hope you can help me

**Comment by nimoatwoodway** [comment]
Are you behind a reverse proxy installation? I had the same problem with an nginx reverse proxy. Setting these to values fixed it for me:

server {
  ....
  client_max_body_size 10G;
  client_body_buffer_size 400M;
  ....
}

**Comment by Bosstox** [comment]
No I don't run a reverse proxy. 
Yesterday i tried the plugin installation. Same problem with the plugin.

**Comment by danb35** [comment]
I just tried a clean installation of this, and I'm able to upload files > 7 GB through the web interface without issues.

**Comment by Bosstox** [comment]
I made now a clean Freenas & Nextcloud installation. I have now massive errors in the httpd-error.log.
[Tue May 14 10:01:02.640545 2019] [proxy_fcgi:error] [pid 69783:tid 34468948736] (70007)The timeout specified has expired: [client 193.187.219.4:53230] AH01075: Error dispatching request to : (reading input$ $ input brigade)

i tried to fix this by setting higher timeout und proxy timeout settings but nothing happend.

**Comment by Bosstox** [comment]
I found the Problem. It was my hardware. i got a issue with my ram. 
danb thank you for the script :)

**Comment by danb35** [comment]
Hardware will do it.  Thanks for the update, I was stumped.  Try my nextcloud-16-caddy branch when you get back up and running.

**Comment by Bosstox** [comment]
It’s maybe a dumb question but what is the diffrence between the normal Nextcloud 16 and the Nextcloud 16 caddy?

**Comment by danb35** [comment]
The -caddy branch uses [Caddy](https://caddyserver.com/) as the web server rather than Apache.  This greatly simplifies configuration, and Caddy directly handles obtaining your cert and all the relevant configuration.  I'm planning to make this the master branch shortly, but it'd be nice to have some further testing.

**Comment by Bosstox** [comment]
Update to my Issue.

New Ram is installed. Installation of the master branch went easy going :). Everything is working. 

Thank you Dan for the script.
