### ISSUE TITLE
Updating mariaDB [question]

### ISSUE THREAD

**Issue by Jacopx** [danb35/freenas-iocage-nextcloud#64]
Hi @danb35, thanks for the script first of all! ;)

I'm here to asking a question, what is the most secure and best way to update mariaDB within a Jail already in production?
Is there any particular reason to do/not do that?

Thanks in advance, it could be a silly question!

**Comment by danb35** [comment]
Updating within MariaDB releases is simple, just run `pkg upgrade` in the jail.  Upgrading between releases (from 10.1 to 10.2, for example) I'd expect to be more problematic, as FreeBSD packages them with different names (`mariadb101-server` vs. `mariadb102-server`).  I'm sure there's a way to upgrade between these, but I'm not sure what it is.

**Comment by Jacopx** [comment]
Thanks anyway, I will search for a solution! 👍
