### ISSUE TITLE
Fresh install, webserver not running

### ISSUE THREAD

**Issue by mattmichaels** [danb35/freenas-iocage-nextcloud#68]
I ran through the script, everything returned as a success. 

CloudFlare shows my site as offline, and browsing out to the local IP shows the site refused to connect.

My redacted install config:

```
JAIL_IP="192.168.0.3"
DEFAULT_GW_IP="192.168.0.1"
POOL_PATH="/mnt/NAS-pool"
TIME_ZONE="America/New_York"
HOST_NAME="XXXXX"
DNS_CERT=1
CERT_EMAIL="XXXXXX@gmail.com"
DNS_PLUGIN="cloudflare"
DNS_ENV="CLOUDFLARE_EMAIL=XXXXX@gmail.comCLOUDFLARE_API_KEY=XXXXXXXXXXX"
DB_PATH="$POOL_PATH/nextCloud/db"
FILES_PATH="$POOL_PATH/nextCloud/files"
PORTS_PATH="$POOL_PATH/nextCloud/portsnap"

```

Running FreeNAS 11.2-U4.1

**Comment by danb35** [comment]
> DNS_ENV="CLOUDFLARE_EMAIL=XXXXX@gmail.comCLOUDFLARE_API_KEY=XXXXXXXXXXX"
There needs to be a space between the email and the API key--if that's missing, that would explain what you're seeing.  If it's there, you should see an error message in `/var/log/caddy.log` in the jail--what's it saying?

**Comment by armanperalta** [comment]
I have the same problem. Connection refuse both on jail ip and hostname.
Jail status is UP and I can ping it.

Config file
`JAIL_IP="10.0.1.10"
DEFAULT_GW_IP="10.0.1.1"
POOL_PATH="/mnt/nas1/xxcloud"
TIME_ZONE="Asia/Hong_Kong"
HOST_NAME="xx.xx.xx"
DNS_CERT=1
CERT_EMAIL="xx@gmail.com"
DNS_PLUGIN="cloudflare"
DNS_ENV="CLOUDFLARE_EMAIL=xx@gmail.com CLOUDFLARE_API_KEY=xxxxxxxxxxxx"
JAIL_NAME="xxcloud"
`

Caddy log
`2020/01/07 16:30:35 [INFO] Caddy version: v1.0.4
2020/01/07 16:30:35 [INFO][cache:0xc0000b89b0] Started certificate maintenance routine
Activating privacy features... 2020/01/07 16:30:41 [INFO][xx.xx.xx] Obtain certificate
2020/01/07 16:30:41 [INFO][xx.xx.xx] Obtain: Waiting on rate limiter...
2020/01/07 16:30:41 [INFO][xx.xx.xx] Obtain: Done waiting
2020/01/07 16:30:41 [INFO] [xx.xx.xx] acme: Obtaining bundled SAN certificate
2020/01/07 16:30:42 [INFO] [xx.xx.xx] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387403
2020/01/07 16:30:42 [INFO] [xx.xx.xx] acme: Could not find solver for: tls-alpn-01
2020/01/07 16:30:42 [INFO] [xx.xx.xx] acme: Could not find solver for: http-01
2020/01/07 16:30:42 [INFO] [xx.xx.xx] acme: use dns-01 solver
2020/01/07 16:30:42 [INFO] [xx.xx.xx] acme: Preparing to solve DNS-01
2020/01/07 16:31:13 [INFO] [xx.xx.xx] acme: Cleaning DNS-01 challenge
2020/01/07 16:31:13 [WARN] [xx.xx.xx] acme: error cleaning up: cloudflare: failed to find zone ga.: Zone could not be found 
2020/01/07 16:31:13 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387403
2020/01/07 16:31:14 [ERROR][xx.xx.xx] failed to obtain certificate: acme: Error -> One or more domains had a problem:
[xx.xx.xx] [xx.xx.xx] acme: error presenting token: cloudflare: failed to find zone ga.: Zone could not be found (attempt 1/3; challenge=dns-01)
2020/01/07 16:31:15 [INFO] [xx.xx.xx] acme: Obtaining bundled SAN certificate
2020/01/07 16:31:15 [INFO] [xx.xx.xx] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387504
2020/01/07 16:31:15 [INFO] [xx.xx.xx] acme: Could not find solver for: tls-alpn-01
2020/01/07 16:31:15 [INFO] [xx.xx.xx] acme: Could not find solver for: http-01
2020/01/07 16:31:15 [INFO] [xx.xx.xx] acme: use dns-01 solver
2020/01/07 16:31:15 [INFO] [xx.xx.xx] acme: Preparing to solve DNS-01
2020/01/07 16:31:15 [INFO] [xx.xx.xx] acme: Cleaning DNS-01 challenge
2020/01/07 16:31:16 [WARN] [xx.xx.xx] acme: error cleaning up: cloudflare: failed to find zone ga.: Zone could not be found 
2020/01/07 16:31:16 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387504
2020/01/07 16:31:16 [ERROR][xx.xx.xx] failed to obtain certificate: acme: Error -> One or more domains had a problem:
[xx.xx.xx] [xx.xx.xx] acme: error presenting token: cloudflare: failed to find zone ga.: Zone could not be found (attempt 2/3; challenge=dns-01)
2020/01/07 16:31:17 [INFO] [xx.xx.xx] acme: Obtaining bundled SAN certificate
2020/01/07 16:31:18 [INFO] [xx.xx.xx] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387520
2020/01/07 16:31:18 [INFO] [xx.xx.xx] acme: Could not find solver for: tls-alpn-01
2020/01/07 16:31:18 [INFO] [xx.xx.xx] acme: Could not find solver for: http-01
2020/01/07 16:31:18 [INFO] [xx.xx.xx] acme: use dns-01 solver
2020/01/07 16:31:18 [INFO] [xx.xx.xx] acme: Preparing to solve DNS-01
2020/01/07 16:31:18 [INFO] [xx.xx.xx] acme: Cleaning DNS-01 challenge
2020/01/07 16:31:19 [WARN] [xx.xx.xx] acme: error cleaning up: cloudflare: failed to find zone ga.: Zone could not be found 
2020/01/07 16:31:19 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387520
2020/01/07 16:31:20 [ERROR][xx.xx.xx] failed to obtain certificate: acme: Error -> One or more domains had a problem:
[xx.xx.xx] [xx.xx.xx] acme: error presenting token: cloudflare: failed to find zone ga.: Zone could not be found (attempt 3/3; challenge=dns-01)
2020/01/07 16:31:21 failed to obtain certificate: acme: Error -> One or more domains had a problem:
[xx.xx.xx] [xx.xx.xx] acme: error presenting token: cloudflare: failed to find zone ga.: Zone could not be found
2020/01/07 16:32:11 [INFO] Caddy version: v1.0.4
2020/01/07 16:32:11 [INFO][cache:0xc0001ca320] Started certificate maintenance routine
Activating privacy features... 2020/01/07 16:32:12 [INFO][xx.xx.xx] Obtain certificate
2020/01/07 16:32:12 [INFO][xx.xx.xx] Obtain: Waiting on rate limiter...
2020/01/07 16:32:12 [INFO][xx.xx.xx] Obtain: Done waiting
2020/01/07 16:32:12 [INFO] [xx.xx.xx] acme: Obtaining bundled SAN certificate
2020/01/07 16:32:13 [INFO] [xx.xx.xx] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387702
2020/01/07 16:32:13 [INFO] [xx.xx.xx] acme: Could not find solver for: tls-alpn-01
2020/01/07 16:32:13 [INFO] [xx.xx.xx] acme: Could not find solver for: http-01
2020/01/07 16:32:13 [INFO] [xx.xx.xx] acme: use dns-01 solver
2020/01/07 16:32:13 [INFO] [xx.xx.xx] acme: Preparing to solve DNS-01
2020/01/07 16:32:43 [INFO] [xx.xx.xx] acme: Cleaning DNS-01 challenge
2020/01/07 16:32:44 [WARN] [xx.xx.xx] acme: error cleaning up: cloudflare: failed to find zone ga.: Zone could not be found 
2020/01/07 16:32:44 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387702
2020/01/07 16:32:44 [ERROR][xx.xx.xx] failed to obtain certificate: acme: Error -> One or more domains had a problem:
[xx.xx.xx] [xx.xx.xx] acme: error presenting token: cloudflare: failed to find zone ga.: Zone could not be found (attempt 1/3; challenge=dns-01)
2020/01/07 16:32:45 [INFO] [xx.xx.xx] acme: Obtaining bundled SAN certificate
2020/01/07 16:32:46 [INFO] [xx.xx.xx] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387780
2020/01/07 16:32:46 [INFO] [xx.xx.xx] acme: Could not find solver for: tls-alpn-01
2020/01/07 16:32:46 [INFO] [xx.xx.xx] acme: Could not find solver for: http-01
2020/01/07 16:32:46 [INFO] [xx.xx.xx] acme: use dns-01 solver
2020/01/07 16:32:46 [INFO] [xx.xx.xx] acme: Preparing to solve DNS-01
2020/01/07 16:32:47 [INFO] [xx.xx.xx] acme: Cleaning DNS-01 challenge
2020/01/07 16:32:47 [WARN] [xx.xx.xx] acme: error cleaning up: cloudflare: failed to find zone ga.: Zone could not be found 
2020/01/07 16:32:47 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387780
2020/01/07 16:32:47 [ERROR][xx.xx.xx] failed to obtain certificate: acme: Error -> One or more domains had a problem:
[xx.xx.xx] [xx.xx.xx] acme: error presenting token: cloudflare: failed to find zone ga.: Zone could not be found (attempt 2/3; challenge=dns-01)
2020/01/07 16:32:48 [INFO] [xx.xx.xx] acme: Obtaining bundled SAN certificate
2020/01/07 16:32:49 [INFO] [xx.xx.xx] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387791
2020/01/07 16:32:49 [INFO] [xx.xx.xx] acme: Could not find solver for: tls-alpn-01
2020/01/07 16:32:49 [INFO] [xx.xx.xx] acme: Could not find solver for: http-01
2020/01/07 16:32:49 [INFO] [xx.xx.xx] acme: use dns-01 solver
2020/01/07 16:32:49 [INFO] [xx.xx.xx] acme: Preparing to solve DNS-01
2020/01/07 16:32:49 [INFO] [xx.xx.xx] acme: Cleaning DNS-01 challenge
2020/01/07 16:32:50 [WARN] [xx.xx.xx] acme: error cleaning up: cloudflare: failed to find zone ga.: Zone could not be found 
2020/01/07 16:32:50 [INFO] Deactivating auth: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/31387791
2020/01/07 16:32:50 [ERROR][xx.xx.xx] failed to obtain certificate: acme: Error -> One or more domains had a problem:
[xx.xx.xx] [xx.xx.xx] acme: error presenting token: cloudflare: failed to find zone: Zone could not be found (attempt 3/3; challenge=dns-01)
2020/01/07 16:32:51 failed to obtain certificate: acme: Error -> One or more domains had a problem:
[xx.xx.xx] [xx.xx.xx] acme: error presenting token: cloudflare: failed to find zone: Zone could not be found`

Freenas version
`FreeNAS-11.2-U6`

**Comment by xames81** [comment]
Where is that log exactly?

/var/log/caddy.log

Thanks.

**Comment by danb35** [comment]
> Where is that log exactly?

It's inside the jail, at the file name you copied and pasted.

**Comment by danb35** [comment]
Closing due to no response.
