### ISSUE TITLE
Error 504 time out

### ISSUE THREAD

**Issue by Adecarcer** [danb35/freenas-iocage-nextcloud#70]
Hello,

I've installed the script several times (superb job!) on my freenas server and always happens the same.

The resulting installed nextcloud server is sluggish and throws back constant time out errors, making it totally unusuable.

If I install the pluging version. it works like a charm (although no https version then :( )

I'm I doing something stupid or wrong.??

thanks for the wonderful work.

**Comment by Ornias1993** [comment]
I've checked and rechecked this multiple times.
Even behind multiple reverse proxy servers and cloudflare.
First load is a little sluggish as it fills the redis cache, after it's quite smooth.

Cant reproduce.
Would you mind adding some logs and/or reproduction instructions? Or mind closing the issue as it can't be reproduced on current version? @Adecarcer ?

**Comment by Adecarcer** [comment]
Hello Ornias.

Thank you for coming back, I've just give up trying to fix this issue.
Definitely there must be something wrong in my network configuration and I've decided to do a real clean install of everything (even resetting routers and firewall rules).

Back to basics to see if it works.

Thank you again for the excellent job and for the answer.
