### ISSUE TITLE
N'autorise pas la connexion.

### ISSUE THREAD

**Issue by nicolas5501** [danb35/freenas-iocage-nextcloud#71]
Hello, can you help me ?

Script run but Web don't work.
i put config file and the error whitch i see.

I get all puty log install if you need it.

Thanks.

### % cat nextcloud-config
JAIL_IP="192.168.1.72"
DEFAULT_GW_IP="192.168.1.254"
POOL_PATH="/mnt/Vol_1"
TIME_ZONE="Europe/Paris"
HOST_NAME="cloud.nd30.fr"
STANDALONE_CERT=1
CERT_EMAIL="admin@nd30.fr"
JAIL_NAME="Cloud"

**I see this error near finish** 

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /usr/local/www/nextcloud/lib/private/Console/Application.php:166
Stack trace:
#0 /usr/local/www/nextcloud/console.php(96): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /usr/local/www/nextcloud/occ(11): require_once('/usr/local/www/...')
#2 {main}
Your data directory is readable by other users
Please change the permissions to 0770 so that the directory cannot be listed by other users.

**Comment by danb35** [comment]
What happens if you `chmod 770 /mnt/Vol_1/files` and then re-run the script?

**Comment by nicolas5501** [comment]
Thx for reply.
"CHMOD Operation not permitted"
https://www.system-linux.eu/index.php?post/2016/04/25/Gestion-des-ACL-Linux

I don't know when and how i change something to loose this ability.

**Comment by danb35** [comment]
The output you show of `ls` indicates that you're using Windows permissions on the files directory/dataset, which is going to cause the problem you're seeing (you have that setting on the db and portsnap datasets as well, which isn't ideal, but isn't likely to cause a problem).  You should use the FreeNAS GUI to set that dataset to Unix permissions.

**Comment by Ornias1993** [comment]
@nicolas5501 Also, your link is about Linux. FreeNAS and this script are not Linux Based.

Anyhow, what @danb35 says would most certainly be the cause of this.
Considering you didn't respond anymore I guess this is solved and could be closed.
