### ISSUE TITLE
Impossible to access nextcloud web page on https

### ISSUE THREAD

**Issue by nicolas5501** [danb35/freenas-iocage-nextcloud#72]
I need help for configure access on Nextcloud web page on https

my domain name  xxx.fr => my own NS

on my NS, a Zimbra mail server is up and use https.
on my freenas nextcloud on a jail and my server on a VM.

When Nextcloud was on http i can join both, since i put Nextcloud on https, i access zimbra but error on NextCloud.

Can you help me?

**Comment by Ornias1993** [comment]
Okey, both the english and the tech is hard to understand here.

Without any details this might just as well be closed.

Wat is the error, wat is the config and why are you running a mailserver on a nameserver?
