### ISSUE TITLE
[QUESTION] Which documentation to follow?

### ISSUE THREAD

**Issue by WilbertNL** [danb35/freenas-iocage-nextcloud#76]
Hi Danb35,

Just a quick question: which install instructions should I follow? The one here on github or the one posted on the Freenas forum?

I ask because I see some differences in the reccomendations, e.g.:
[https://www.ixsystems.com/community/resources/scripted-installation-of-nextcloud-17-in-iocage-jail.90/](url)

> It's also preferred to have three datasets created on your pool: files (for the Nextcloud data files), db (for the MariaDB database files), and portsnap (for the FreeBSD ports collection). If you do create these datasets, for best performance, set atime to off for files and db, and set the record size for db to 16 KB (this can be found in the Advanced settings). If you don't create these datasets, the script will create directories on your pool instead.

Whereas
[https://github.com/danb35/freenas-iocage-nextcloud](url)

> Although not required, it's recommended to create two datasets on your main storage pool: one named files, which will store the Nextcloud user data; and one called db, which will store the SQL database. For optimal performance, set the record size of the db dataset to 16 KB (under Advanced Settings in the FreeNAS web GUI). It's also recommended to cache only metadata on the db dataset; you can do this by running zfs set primarycache=metadata poolname/db.

Thanks in advance,
Cheers,
Wilbert

**Comment by WilbertNL** [comment]
Hi Danb35,

Assuming that you must be quite busy, and documentation is the least of your worries, I'd still like to ask you which documentation I should consider using.

If you have a moment...

Thanks!

**Comment by danb35** [comment]
Sorry for the delay in responding; I should have the docs better harmonized.  The three-dataset approach is better, IMO, though the ports dataset would certainly be the least-important of the three--it could just as well be a subdirectory rather than its own dataset.

**Comment by WilbertNL** [comment]
Thanks!

**Comment by Ornias1993** [comment]
@WilbertNL  Before you close this (and please DO close this after my reply, as your issue has been solved aka your question answered), I want to add something:

The thing with portsnap as a dataset is: It isn't really needed to have it on a seperate dataset. It would work just fine within the jail itself.
However: As soon as you get multiple jails that require portsnap, they would be able to share the data if you give them a shared portsnap dataset.

Lets call it "future proofing" to put portsnap in its own dataset ;) 

I think that answers all questions regarding portsnap, please close the issue now.
