### ISSUE TITLE
Cannot reach my nextcloud instance... restarting Caddy fixes it.

### ISSUE THREAD

**Issue by vroomr** [danb35/freenas-iocage-nextcloud#78]
Have it with some regularity, and I do not know why. 

Try to access my Nextcloud, and it is not running. I enter a shell,  `service caddy restart` and everything is great.

Don't know where to look to fix. Tried adding caddy-restart.sh to crontab, but does not seem to help.

Currently on FreeNAS 11.3 Beta, with NC17.

**Comment by danb35** [comment]
> Don't know where to look to fix.

Start with the Caddy log at /var/log/caddy.log--it should tell you why it's
stopping.

**Comment by vroomr** [comment]
hmmmm. Currently not working. Last lines are:
`
2019/12/13 03:56:16 set tcp 192.XXX.XXX.XXX:XXXX->82.202.249.205:39251: setsockopt: connection reset by peer
2019/12/13 04:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 04:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 05:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 05:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 06:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 06:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 07:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 07:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 08:21:56 [INFO][cache:0xc0000d2a50] Scanning for expiring certificates
2019/12/13 08:21:56 [INFO][cache:0xc0000d2a50] Done scanning certificates
2019/12/13 08:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 08:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 09:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 09:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 10:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 10:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 11:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 11:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 12:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 12:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 13:21:56 [INFO][cache:0xc0000d2a50] Scanning for stale OCSP staples
2019/12/13 13:21:56 [INFO][cache:0xc0000d2a50] Done checking OCSP staples
2019/12/13 13:50:32 [INFO] SIGTERM: Shutting down servers then terminating
2019/12/13 13:50:32 [INFO][cache:0xc0000d2a50] Stopped certificate maintenance routine
`



Also, maybe noteworthy, maybe not, but there is lots of noise about stuff not  looking like a TLS handshake.

`2019/12/13 03:55:30 http: TLS handshake error from 76.65.215.21:48796: tls: first record does not look like a TLS handshake
2019/12/13 03:55:31 http: TLS handshake error from 93.115.28.171:63375: EOF
2019/12/13 03:55:36 http: TLS handshake error from 139.162.108.129:38768: EOF
2019/12/13 03:55:36 http: TLS handshake error from 139.162.108.129:44472: tls: first record does not look like a TLS handshake
2019/12/13 03:55:42 http: TLS handshake error from 139.162.108.129:44562: unexpected EOF
2019/12/13 03:55:42 http: TLS handshake error from 139.162.108.129:46506: tls: first record does not look like a TLS handshake
2019/12/13 03:55:42 http: TLS handshake error from 139.162.108.129:46690: tls: first record does not look like a TLS handshake
2019/12/13 03:55:48 http: TLS handshake error from 112.85.42.195:64418: tls: first record does not look like a TLS handshake
`

Any ideas?

**Comment by Ornias1993** [comment]
Are you connecting using your domainname/hostname?

**Comment by Ornias1993** [comment]
Okey looking at this again we need a few things to be able to help and/or reproduce:
1. Your config for running this script.
2. The error log (including startup of caddy would be nice)

Tried installing with quite a few configurations... Never had this issue.

**Comment by Ornias1993** [comment]
@vroomr I know yours issue:
`2019/12/13 03:55:30 http: TLS handshake error from 76.65.215.21:48796: tls: first record does not look like a TLS handshake `

Is the error you get when SNI mismatches. This happens for example when you put a reverse proxy in front of Nextcloud that doesn't forward SNI correctly.

Simply put:
Caddy (by default) requires the SSL request to include a reference to the domain name, if it doesn't it freaks out. A fix for this is to set "default-sni" in the caddy config. Sadly enough @danb35 Rejected my proposal to include this. But that being said: This most likely your issue and/or your solution.

As this is quite old, you got a proposed solution now and we didn't hear anything, I think this can be closed... agree @danb35  ?

**Comment by vroomr** [comment]
Thanks @Ornias1993 . Good with me to close it :)
