### ISSUE TITLE
security/performance issues with default install

### ISSUE THREAD

**Issue by airflow2010** [danb35/freenas-iocage-nextcloud#80]
After deploying the nextcloud-instance with this script, there are two warnings reported by the instance itself (under admin/settings/administration/overview):

- The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
- Some columns in the database are missing a conversion to big int.

Both issues can be easily fixed:

For the first issue, add
`X-Frame-Options                         "SAMEORIGIN"`
in the "header" section of the Caddyfile.

For the second issue, execute
`sudo -u www php /usr/local/www/nextcloud/occ db:convert-filecache-bigint
`
once after install.

**Comment by danb35** [comment]
The header is an easy enough fix.  I recall putting the database conversion (which leaves aside the question of why a "conversion" is required in the first place, in a brand-new database created directly by Nextcloud--why isn't it created with big int in the first place?) in the script, but taking out because it wouldn't run non-interactively--it required user input to run.  Is this no longer the case?

**Comment by airflow2010** [comment]
This is true, the second command requests user confirmation for the convertion of the database. I don't know if there is a switch to turn it non-interactive. If the database is already in the right format however, the command exits cleanly without interaction. To my mind it would be OK to have the administrator confirm this step, but this is your call.

**Comment by Migsi** [comment]
[This link](https://docs.nextcloud.com/server/17/admin_manual/configuration_database/bigint_identifiers.html) consideres there is a flag to be set for non interactive mode.

**Comment by danb35** [comment]
Ah, I hadn't seen that earlier.  This should be fixed now.

**Comment by Migsi** [comment]
> After deploying the nextcloud-instance with this script, there are two warnings reported by the instance itself (under admin/settings/administration/overview):
> 
>     * The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
> 
>     * Some columns in the database are missing a conversion to big int.
> 
> 
> Both issues can be easily fixed:
> 
> For the first issue, add
> `X-Frame-Options "SAMEORIGIN"`
> in the "header" section of the Caddyfile.
> 
> For the second issue, execute
> `sudo -u www php /usr/local/www/nextcloud/occ db:convert-filecache-bigint `
> once after install.

Regarding the X-Frame-Options, I was unable to fix that by just adjusting the Caddyfile under /usr/local/www/. Is there another Caddyfile which needs to be changed?

**Comment by danb35** [comment]
That sounds like the Nextcloud security scanner is being overly picky.  Notably, the Nextcloud installation itself doesn't give this complaint:
![image](https://user-images.githubusercontent.com/12121759/73616061-c47efe00-45dc-11ea-99ca-5298f55e45cd.png)

**Comment by Ornias1993** [comment]
@danb35 I tested the last 2 versions, both passed both the internal security check AND the Nextcloud Security Scanner.... So this seems solved.

Unless @Migsi Still has this issue, But in that case I doubt it's a code issue in this script to be honest

**Comment by Migsi** [comment]
> @danb35 I tested the last 2 versions, both passed both the internal security check AND the Nextcloud Security Scanner.... So this seems solved.
> 
> Unless @Migsi Still has this issue, But in that case I doubt it's a code issue in this script to be honest

As I stated in the EDIT 2 in my last post, the problem was not really related to the script, but to the pickyness of the online nextcloud security scanner, which just didn't like the all uppercase header field. So the problem can be solved by adjusting the script, but IMHO should be fixed by nextcloud, adjusting their scanner to be case insensitive.
