### ISSUE TITLE
php73-memcache failed to install

### ISSUE THREAD

**Issue by MarpleA** [danb35/freenas-iocage-nextcloud#81]
the installation process cant find the - php73-memcache package

```
  - php73-exif...
  - php73-gmp...
  - php73-memcache...
    - php73-memcache failed to install, retry #1
    - php73-memcache failed to install, retry #2
    - php73-memcache failed to install, retry #3
pkg: No packages available to install matching 'php73-memcache' have been found in the repositories
  - php73-opcache...
  - php73-pcntl...
  - php73-pecl-imagick...
```

the installation completes without any further error messages, however most likely due to this error I am not able to access the webui.
I am running FreeNAS 11.2U7

any ideas?

**Comment by LukeRhok** [comment]
I saw the same failed installs during my installation today. What error are you getting when you try to connect to your server with your hostname?  I'm getting Error 521 through Cloudflare.

**Comment by jakc664** [comment]
I got the same error as well. I think that the package for "php73-memcache" was changed/named something different. My theory is that if one could find the correct package, that it could be manually installed via "pkg" to see if that fixes the error.

>Internal Server Error
>The server encountered an internal error and was unable to complete your request. Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report. More details can be found in the server log.

**Comment by kevinljxljx** [comment]
It seems like php73-memcache was retired and removed on 30 Dec 2019 https://www.freshports.org/databases/php-memcache/
The new package is called pecl-memcache https://github.com/websupport-sk/pecl-memcache
https://www.freebsd.org/cgi/ports.cgi?query=pecl-memcache&stype=all

**Comment by danb35** [comment]
The correct package name to install is now php73-pecl-memcache; the script has been updated to reflect this change.
