### ISSUE TITLE
LAN access 

### ISSUE THREAD

**Issue by The-Jaeger** [danb35/freenas-iocage-nextcloud#83]
I initially ran the script to have access through a domain, but now I want to configure it to only be accessible from the lan with just the lan IP. I'm looking through the Caddyfile and every file in /usr/local/www/nextcloud/ and I do not see an equivalent nginx/html/apache config file to adjust the settings for https access.

I currently get this error when trying to access it from the lan: 404 Site 192.168.1.12 is not served on this interface. (http)
I get this error when attempting to access https://192.168.1.7  : This site can't provide a secure connection

**Comment by danb35** [comment]
The Caddyfile (the web server configuration file) is, by default, designed to only be accessed by the hostname.  You can edit it to use the IP address, but you'll lose SSL unless you use a self-signed certificate (no CA will issue a cert for your internal IP address, so you'd have certificate errors).

Use the Caddyfile-nossl file as an example, but in short, you'd make two changes:

* Remove the `tls` configuration block
* Change the domain name on the first line to 192.168.1.7:80

You can find the Caddyfile in the jail at `/usr/local/www/Caddyfile`.

**Comment by Ornias1993** [comment]
@danb35 I think your advice was pretty clear (and its not a bug), I think this can also be byebye (closed)...
