### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by FernandoGambaro** [danb35/freenas-iocage-nextcloud#84]
Hi there, i get this error when finish a fresh installation, Caddyfile seems to be fine.

In the Jail configuration the IPv4 is set manually,  

Any idea?

Thanks.

**Comment by Ornias1993** [comment]
These errors mostly happen when a reverse proxy doesn't get a response in time from the actual webserver....

**Comment by danb35** [comment]
I'm going to guess that the memcache module failed to install.  Enter the jail, then run `pkg install php73-pecl-memcache`.  Then do `service caddy restart` and see if it works.

**Comment by Ornias1993** [comment]
Agreed, memcache shares some similarities with reverse proxies and considering the recent memcache changes that seems reasonable.

**Comment by Ornias1993** [comment]
Another issue that might create this is if you setup redis and it failed to load/connect correctly.

But considering the creater of this issue isn't responding anymore, I think this can be closed @danb35

**Comment by danb35** [comment]
Concur.  @FernandoGambaro, if you're still having problems, let me know what the result was of what I suggested on 1/31 and I can re-open.
