### ISSUE TITLE
DNS Issue

### ISSUE THREAD

**Issue by jacobq11** [danb35/freenas-iocage-nextcloud#86]
There needs to be and option to set the resolver or nothing will install.

I was able to get it fixed by editing the script and changed the jail creations to DHCP since I have everything reserved there.

**Comment by jacobq11** [comment]
Sorry I posted it twice.

**Comment by danb35** [comment]
Is this something that has changed in 11.3?  Because it's worked fine on 11.1 and 11.2 without explicitly setting a DNS server--iocage has apparently been treating the default gateway as the resolver.

**Comment by Ornias1993** [comment]
@danb35 building multiple jails on 11.3 and 11.2, I can for sure say no relevant changes are done requiring DNS server specifications for jails under 11.3 specifically.

Though I personally prefer DHCP and fixed leases for everything except primary networking devices.

**Comment by jacobq11** [comment]
I was testing on 11.2u6. my issue probably lies in the fact that I have a dedicated DNS server on my network that isn't using the same IP as my gateway

**Comment by airflow2010** [comment]
When I use the script (and also for any other jail creations I do myself), the jail seems to inherit the DNS-configuration of the host. /etc/resolv.conf looks exactly the same in host and jail.

**Comment by Ornias1993** [comment]
> When I use the script (and also for any other jail creations I do myself), the jail seems to inherit the DNS-configuration of the host. /etc/resolv.conf looks exactly the same in host and jail.

It does :)

**Comment by Ornias1993** [comment]
@danb35 As jails inherit DNS from the host when set to Static IP, I see no reason this is in any way, shape or form this is related to the script. Neither does iocage have a hook to input this on jail creation (1)

Thus this can be closed safely.

(1) we could hack it in, but I really, really doubt we want to create a fix to cover for users with wrong/strange DNS configuration in their freenas host
