### ISSUE TITLE
Include update script for existing installations

### ISSUE THREAD

**Issue by Ornias1993** [danb35/freenas-iocage-nextcloud#88]
It would be nice if an update script could be included to also keep current installations up to date.
Or would just pkg upgrading + nextcloud update it really be all thats needed?

**Comment by danb35** [comment]
> Or would just pkg upgrading + nextcloud update it really be all thats needed?

I'd think it would be, as long as the base FreeBSD version is supported.  And since you can upgrade the iocage jail to the current release once it changes, I'm not sure that any kind of upgrade script I could provide would be very useful.  Or were you thinking of something different?

**Comment by Ornias1993** [comment]
No that would be it, if its that easy... 
There really is no need and it would increase the mainenance requirements
