### ISSUE TITLE
Script fails when IP configuration is bound to secondary bridge

### ISSUE THREAD

**Issue by kleinarne** [danb35/freenas-iocage-nextcloud#92]
I tried running the script on FreeNAS 11.2-U8.

My FreeNAS host has two NICs (igb0, igb1) connected to two managed switch ports that tag packets for different VLANs, one for internal LAN (10.0.0.0/24), one for a DMZ (10.0.1.0/24). I use tunables to create bridge1 and add igb1 to that bridge, but I don't know how to tell the script to add the jail to bridge1. 

The jail then has a 10.0.1.2 IP but it's in the 10.0.0.0/24 VLAN, so it stops when testing connectivity to pkg.freebsd.org.

Is there any way to tell the script to attach the VNET to another bridge that bridge0?

**Comment by Ornias1993** [comment]
iocage create ... interfaces="vnet0:bridge99" ...

Thats it :)

**Comment by Ornias1993** [comment]
@kleinarne I'll make a PR for this, it's 2 minutes work. (as I already did it for my jail manager ( https://github.com/Ornias1993/jailman), So I can port the code to this script for you: )

**Comment by Ornias1993** [comment]
Done, writing a description took more time than the actual fix.
