### ISSUE TITLE
Problem with assigned IP when installing?

### ISSUE THREAD

**Issue by MyHaven** [danb35/freenas-iocage-nextcloud#99]
I have assigned IP in the config file, and it reads:

JAIL_IP="192.168.1.75"

However when I run ./nextcloud-jail.sh
I get the following message:
Please provide a valid ip: Only decimal digits permitted in '75\r' in 192.168.1.75\r'

**Comment by MyHaven** [comment]
I found the solution! I was creating the textfile in Notepad++ in windows, and the line break in Windows is apparently different from Unix. 

I finally found the solution here:
https://www.ixsystems.com/community/resources/why-does-editing-a-freenas-script-text-file-on-a-windows-pc-cause-issues-when-copied-to-nas.67/

First I suspected charset to be the issue, but it was a matter of converting the document line breaks from CR LF to LF

**Comment by danb35** [comment]
Notepad++ is a good editor, and I'm sure there's a way to fix the newlines in it, but yes, this is a common problem when using Windows-based editors for files on *nix systems.
